### PR TITLE
Correction of a typo

### PR DESCRIPTION
**Pull request by nokibsarkar**
the first letter was somehow missing

### CODE REVIEW

**Comment by dralshehri** [comment]
In `develop` branch, locales have been refactored for the next release. Please check if you still need this fix. If so, choose the `develop` branch for your pull request. Thanks!

**Comment by nokibsarkar** [comment]
Ok no problem.

**Comment by dralshehri** [comment]
@nokibsarkar For the sake of deep understanding, could you tell me what might be the differences between the two locales in our case? I mean Hijri months and week days.

**Comment by nokibsarkar** [comment]
Ok. Actually they are from two different cultural society. The first (``bn-BD`` that is Muslim dominated Bangla used by  Bangladeshis) often use arabic transliterations as is (as much possible). But in the later case (``bn-IN`` that is Hindu dominated Bangla used by Indian Bangalis) might use the transliterations differently, but I cannot assure because I came from the first group. Though there is no significant difference, there is somewhat significant infuence of religion on language. I will try to dig up if possible.

**Comment by dralshehri** [comment]
Thank you for clarification. I'm going to close this request for now and I'll let you know when there is any update for review.

**Pull request closed without merging**
